<?php
// module/Album/view/album/album/index.phtml:
    $title = 'Gallery';
    $this->headTitle($title);
?>
<style>
    img.text-center{
        max-height:500px;
        max-width:500px;
        height:auto;
        width:auto;
    }
</style>


<div class="m-5">
    <div class="justify-center">
        <p class="text-2xl" id="imgName"><?= $picture->name ?></p>
        <a href="<?=$this->url('photo',['action'=>'add']);?>" class="fas fa-plus-circle"></a>
        <a href="<?=$this->url('photo',['action'=>'delete','id'=>$picture->id]);?>" id="deleteImg" class="fas fa-trash"></a>
    </div>
    <p class="hidden" id="error"></p>
    <?php if($picture->encode_photo):?> 
        <center><img class="border border-red-400" id="img" src="data:image/png;base64,<?= $picture->encode_photo?>"/></center> 
    <?php else:?>
        <p>Gallery is empty</p>
    <?php endif; ?>
    
</div>

<div>
    <a href="<?=$this->url('photo',['action'=>'prev', 'id'=> $picture->id-1]);?>" class="bg-blue-200 rounded" id="prevImg">Previous Image</a>
    <a href="<?=$this->url('photo',['action'=>'next', 'id'=> $picture->id+1]);?>" class="bg-blue-200 rounded" id="nextImg">Next Image</a>
</div>

<?=
   $this->inlineScript()->prependFile($this->basePath('js/btnHandler.js'));
?>